### ISSUE TITLE
When i  use with mptcp, but only 1 flow is transmitting?

### ISSUE THREAD

**Issue by Sean861026** [dreibh/netperfmeter#3]
and it tell me two warning
1.Failed to set MPTCP_PATH_MANAGER on MPTCP socket - Operation mot permitted
2.Failed to set MPTCP_SCHRDULER on MPTCP socket - Operation mot permitted

why?
i use netperfmeter in mininet-wifi

**Comment by dreibh** [comment]
Could you provide some details:
- Kernel version
- MPTCP patch version

Is the kernel providing MPTCP support (NetPerfMeter can only use MPTCP when the kernel provides it)?
